# pull official base image
# build environment
FROM node:13.12.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.3 -g --silent

# add app
COPY . ./
RUN npm run build

# production environment


# pull nginx Base Image
FROM nginx:stable-alpine

# Copy Build folder from Build session
COPY --from=build /app/build /usr/share/nginx/html


#This would only expose port that is required
EXPOSE 8081

# Run Command
CMD ["nginx", "-g", "daemon off;"]
